Convenience/Models/Properties/Zaiko.cs
using Convenience.Data;
using Convenience.Models.DataModels;
using Convenience.Models.Interfaces;
using Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using System.Collections.Immutable;
using System.Linq;
using System.Linq.Expressions;
using System.Linq.Dynamic.Core;
using static Convenience.Models.ViewModels.Zaiko.ZaikoViewModel;

namespace Convenience.Models.Properties {

    /// <summary>
    /// 注文実績明細検索＆倉庫在庫（遅延実行）
    /// </summary>
    public class Zaiko : IZaiko {

        /// <summary>
        /// DBコンテキスト
        /// </summary>
        private readonly ConvenienceContext _context;
        /// <summary>
        /// 生成される問い合わせ（遅延実行用）
        /// </summary>
        public IQueryable<ZaikoListLine>? SoKoZaikoQueryable { get; set; } = null;
        /// <summary>
        /// OrderByかThenByか切り替えるフラグ
        /// </summary>
        bool isFirstCalled = true;  //true->Orderby false->ThenBy

        /// <summary>
        /// コンストラクター（コンソール実行＝デバッグ用）
        /// </summary>
        public Zaiko() {
            IConfiguration configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .Build();

            DbContextOptions<ConvenienceContext> contextOptions = new DbContextOptionsBuilder<ConvenienceContext>()
                .UseNpgsql(configuration["ConvenienceContext"])
                .Options;

            _context = new ConvenienceContext(contextOptions);
        }

        /// <summary>
        /// ＤＢコンテキスト設定（ＡＳＰ実行用）
        /// </summary>
        /// <param name="context"></param>
        public Zaiko(ConvenienceContext context) {
            _context = context;
        }

        /// <summary>
        /// 注文実績明細検索＆倉庫在庫（遅延実行）
        /// </summary>
        /// <param name="inSearchKey">検索キー</param>
        /// <returns>倉庫在庫　＆　注文実績明細(変数:SoKoZaikoQueryable) Where指示付き　ISoKoZaikoQueryable型にして遅延実行化</returns>
        public IQueryable<ZaikoListLine> CreateSokoZaikoList(string inSearchKey) {

            //検索処理初回か？　nullの場合初回
            //Whereが複数セットされるが、セットのたびにこのメソッドはコールされるため、初回判断が必要
            if (SoKoZaikoQueryable == null) {

                //初回の場合は、注文実績と倉庫在庫を結合するLinq実行
                //注文実績検索（遅延実行）
                IQueryable<ChumonJissekiMeisai> chumonJissekiQueryable = _context.ChumonJissekiMeisai.AsNoTracking()
                .Where(x => x.ChumonZan > 0)
                .GroupBy(gr => new { gr.ShiireSakiId, gr.ShiirePrdId, gr.ShohinId })
                .Select(s => new ChumonJissekiMeisai { ShiireSakiId = s.Key.ShiireSakiId, ShiirePrdId = s.Key.ShiirePrdId, ShohinId = s.Key.ShohinId, ChumonSu = s.Sum(item => item.ChumonSu), ChumonZan = s.Sum(item => item.ChumonZan) })
                .AsQueryable();

                //倉庫在庫検索（遅延実行）
                SoKoZaikoQueryable = _context.SokoZaiko.AsNoTracking()
                    .Include(i => i.ShiireMaster).ThenInclude(j => j!.ShohinMaster)
                    .GroupJoin(chumonJissekiQueryable,
                            soko => new { soko.ShiireSakiId, soko.ShiirePrdId, soko.ShohinId },
                            cjm => new { cjm.ShiireSakiId, cjm.ShiirePrdId, cjm.ShohinId },
                            (soko, cjm) => new { soko, cjm })
                    .SelectMany(
                            soko => soko.cjm.DefaultIfEmpty(),
                            (soko, cjm) => new ZaikoListLine {
                                ShiireSakiId = soko.soko.ShiireSakiId,
                                ShiirePrdId = soko.soko.ShiirePrdId,
                                ShohinId = soko.soko.ShohinId,
                                ShohinName = soko.soko.ShiireMaster!.ShohinMaster!.ShohinName,
                                SokoZaikoCaseSu = soko.soko.SokoZaikoCaseSu,
                                SokoZaikoSu = soko.soko.SokoZaikoSu,
                                LastShiireDate = soko.soko.LastShiireDate,
                                LastDeliveryDate = soko.soko.LastDeliveryDate,
                                ChumonZan = cjm!.ChumonZan
                            })
                    .AsQueryable();
            }

            //inSearchKeyによるwhereの設定
            //初回のみならず、メソッド実行のたびに、whereが追加される
            SoKoZaikoQueryable = !string.IsNullOrEmpty(inSearchKey) ?
                SoKoZaikoQueryable = SoKoZaikoQueryable.Where(inSearchKey).AsQueryable() : SoKoZaikoQueryable;

            //Linqの結果返却（まだ、EFは実行されていない）
            //倉庫在庫　＆　注文実績明細(Where指示付き）
            return SoKoZaikoQueryable;
        }

        /// <summary>
        ///  機能：注文実績明細検索＆倉庫在庫（遅延実行）＋Where内容の状態から、ソート順の追加セットを行う
        /// </summary>
        /// <param name="sortKey">ソートキー</param>
        /// <param name="descending">降順・昇順区分</param>
        /// <returns>倉庫在庫　＆　注文実績明細(変数:SoKoZaikoQueryable) ソート指示付き　ISoKoZaikoQueryable型にして遅延実行化</returns>
        public IQueryable<ZaikoListLine>? AddOrderby(string sortKey, bool descending) {

            //倉庫在庫の検索指示があるかどうか。あればオーダー設定を追加する   
            if (SoKoZaikoQueryable != null) {

                //ソートキーの昇順・降順設定（遅延実行）
                IQueryable<ZaikoListLine>? orderQueryable;
                
                if (isFirstCalled) {
                    //初回であれば、OrderBy
                    if (descending) {
                        //降順
                        orderQueryable=SoKoZaikoQueryable.OrderBy(sortKey + " descending");
                    }
                    else {
                        //昇順
                        orderQueryable=SoKoZaikoQueryable.OrderBy(sortKey);
                    }
                }
                else {
                    //２回目以降、ThenBy
                    if (descending) {
                        //降順
                        orderQueryable=((IOrderedQueryable<ZaikoListLine>)SoKoZaikoQueryable).ThenBy(sortKey + " descending");
                    }
                    else {
                        //昇順
                        orderQueryable=((IOrderedQueryable<ZaikoListLine>)SoKoZaikoQueryable).ThenBy(sortKey);
                    }
                }

                //ソート指示追加(まだ実行されない）
                SoKoZaikoQueryable = orderQueryable?.AsQueryable();

                //１回処理されれば、次回はThenByになるように
                isFirstCalled = false;
            }
            //倉庫在庫　＆　注文実績明細　ソート指示付き
            return SoKoZaikoQueryable;
        }
    }
}

Convenience/Models/ViewModels/Zaiko/ZaikoViewModel.cs
using Convenience.Models.DataModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;

namespace Convenience.Models.ViewModels.Zaiko {
    /// <summary>
    /// 在庫検索用ビューモデル
    /// </summary>
    public class ZaikoViewModel {
        /// <summary>
        /// コンストラクタ（なし）
        /// </summary>
        public ZaikoViewModel() {
        }

        /// <summary>
        /// ソートキー選択結果セット用
        /// </summary>
        [DisplayName("ソートキー")]
        public class KeyEventRec {
            [DisplayName("ソート項目")]
            public string? KeyEventData { get; set; }
            [DisplayName("昇順・降順")]
            public bool Descending { get; set; } = false;
        }
        /// <summary>
        /// ソート指示項目の最大値
        /// </summary>
        const int LineCountForSelectorOfOderBy = 3;    //ソート用３つまで入力ＯＫ
        /// <summary>
        /// ソートキー選択結果セット用を使ってリストを初期化
        /// </summary>
        public KeyEventRec[] KeyEventList { get; set; } = Enumerable.Range(0, LineCountForSelectorOfOderBy).Select(_ => new KeyEventRec()).ToArray();

        /// <summary>
        /// ソート指示選択用一覧（画面表示と選択用）
        /// </summary>
        public SelectList KeyList = new(
            new List<SelectListItem>
                {
                    new() { Value = nameof(ZaikoListLine.ShiireSakiId), Text = "仕入先コード" },
                    new() { Value = nameof(ZaikoListLine.ShiirePrdId), Text = "仕入商品コード" },
                    new() { Value = nameof(ZaikoListLine.ShohinId), Text = "商品コード" },
                    new() { Value = nameof(ZaikoListLine.ShohinName), Text = "商品名" },
                    new() { Value = nameof(ZaikoListLine.SokoZaikoCaseSu), Text = "在庫数" },
                    new() { Value = nameof(ZaikoListLine.SokoZaikoSu), Text = "倉庫在庫数" },
                    new() { Value = nameof(ZaikoListLine.LastShiireDate), Text = "直近仕入日" },
                    new() { Value = nameof(ZaikoListLine.LastDeliveryDate), Text = "直近払出日" },
                    new() { Value = nameof(ZaikoListLine.ChumonZan), Text = "注文残" },
                }, "Value", "Text");

        /// <summary>
        /// Where指示選択結果セット用
        /// </summary>
        public class SelecteWhereItem {
            [DisplayName("検索項目項目")]
            public string? LeftSide { get; set; }

            [DisplayName("比較")]
            [MaxLength(2)]
            public string? ComparisonOperator { get; set; } = "==";
            [DisplayName("検索キー")]
            public string? RightSide { get; set; }
        }

        /// <summary>
        /// 比較演算子選択用
        /// </summary>
        public SelectList ComparisonOperatorList = new(
            new List<SelectListItem> {
            new (){ Value = "==", Text = "=" },
            new (){ Value = "!=", Text = "!=" },
            new (){ Value = ">=", Text = ">=" },
            new (){ Value = ">", Text = ">" },
            new (){ Value = "<=", Text = "<=" },
            new (){ Value = "<", Text = "<" },
        }, "Value", "Text");

        /// <summary>
        /// Where入力行数
        /// </summary>
        const int LineCountForSelectorOfWhere = 6; //Where入力６行
        /// <summary>
        /// Where入力リスト初期化
        /// </summary>
        public SelecteWhereItem[] SelecteWhereItemArray { get; set; } = Enumerable.Range(0, LineCountForSelectorOfWhere).Select(_ => new SelecteWhereItem()).ToArray();

        /// <summary>
        /// Where左辺用カラムセット用
        /// </summary>
        public SelectList SelectWhereLeftSideList = new (
                new List<SelectListItem>
                    {
                    new() { Value = nameof(ZaikoListLine.ShiireSakiId), Text = "仕入先コード" },
                    new() { Value = nameof(ZaikoListLine.ShiirePrdId), Text = "仕入商品コード" },
                    new() { Value = nameof(ZaikoListLine.ShohinId), Text = "商品コード" },
                    new() { Value = nameof(ZaikoListLine.ShohinName), Text = "商品名" },
                    new() { Value = nameof(ZaikoListLine.SokoZaikoCaseSu), Text = "在庫数" },
                    new() { Value = nameof(ZaikoListLine.SokoZaikoSu), Text = "倉庫在庫数" },
                    new() { Value = nameof(ZaikoListLine.LastShiireDate), Text = "直近仕入日" },
                    new() { Value = nameof(ZaikoListLine.LastDeliveryDate), Text = "直近払出日" },
                    new() { Value = nameof(ZaikoListLine.ChumonZan), Text = "注文残" },
                    }, "Value", "Text");

#pragma warning disable CS8618
        /// <summary>
        /// 倉庫在庫・注文実績明細変策用レコード
        /// </summary>
        public class ZaikoListLine {
            [DisplayName("仕入先コード")]
            public string ShiireSakiId { get; set; }
            [DisplayName("仕入商品コード")]
            public string ShiirePrdId { get; set; }
            [DisplayName("商品コード")]
            public string ShohinId { get; set; }
            [DisplayName("商品名称")]
            public string? ShohinName { get; set; }
            [DisplayName("仕入単位在庫数")]
            public decimal SokoZaikoCaseSu { get; set; }
            [DisplayName("在庫数")]
            public decimal SokoZaikoSu { get; set; }
            [DisplayName("直近仕入日")]
            public DateOnly LastShiireDate { get; set; }
            [DisplayName("直近払出日")]
            public DateOnly? LastDeliveryDate { get; set; }
            [DisplayName("注文残")]
            public decimal? ChumonZan { get; set; }
        }

#pragma warning restore CS8618

        /// <summary>
        /// 倉庫在庫・注文実績明細検索用用レコードのリスト（検索結果がここに入る）
        /// </summary>
        public IList<ZaikoListLine> ZaikoListLines { get; set; } = new List<ZaikoListLine>();

        public ZaikoListLine ZaikoLine { get; set; } = new ZaikoListLine();
    }
}

Convenience/Controllers/ZaikoController.cs
using Convenience.Models.Interfaces;
using Convenience.Models.Properties.Config;
using Convenience.Models.ViewModels.Zaiko;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Convenience.Models.ViewModels.Zaiko.ZaikoViewModel;

namespace Convenience.Controllers {

    /// <summary>
    /// 倉庫在庫検索コントローラ
    /// </summary>
    public class ZaikoController : Controller , ISharedTools {
        //private readonly ConvenienceContext _context;

        private readonly IZaikoService zaikoService;

        /// <summary>
        /// Postデータ引継ぎ用キーワード
        /// </summary>
        private static readonly string IndexName = "ZaikoPostData";

        /// <summary>
        /// CSVファイル作成（ＤＩ用）
        /// </summary>
        private readonly IConvertObjectToCsv _convertObjectToCsv;

        /// <summary>
        /// コンストラクター
        /// </summary>
        /// <param name="zaikoService">在庫サービスクラスＤＩ注入用</param>
        public ZaikoController(IZaikoService zaikoService, IConvertObjectToCsv convertObjectToCsv) {
            this.zaikoService = zaikoService;
            this._convertObjectToCsv = convertObjectToCsv;
        }

        [Authorize]
        public IActionResult Index() {
            ZaikoViewModel zaikoViewModel = new();
            return View(zaikoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(ZaikoViewModel inZaikoModel) {
            KeyEventRec[] keydata = inZaikoModel.KeyEventList;
            SelecteWhereItem[] selecteWhereItemArray = inZaikoModel.SelecteWhereItemArray;

            ZaikoViewModel zaikoViewModel =
                await zaikoService.KeyInput(keydata, selecteWhereItemArray);

            // キーワードエリアの保存
            TempData[IndexName] = ISharedTools.ConvertToSerial(inZaikoModel);

            return View(zaikoViewModel);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DownLoad() {
            ZaikoViewModel viewmodel
                = ISharedTools.ConvertFromSerial<ZaikoViewModel>(TempData.Peek(IndexName)?.ToString() ?? throw new Exception("tempdataなし"));

            KeyEventRec[] keydata = viewmodel.KeyEventList;
            SelecteWhereItem[] selecteWhereItemArray = viewmodel.SelecteWhereItemArray;

            ZaikoViewModel zaikoViewModel =
                await zaikoService.KeyInput(keydata, selecteWhereItemArray);

            //このコントローラの名前を認識
            string fileName = _convertObjectToCsv.GetFileName(this.GetType().Name);

            //モデルデータを取り出すし、ＣＳＶに変換
            IEnumerable<ZaikoListLine> modeldatas = zaikoViewModel.ZaikoListLines;
            string filename = _convertObjectToCsv.ConvertToCSV<ZaikoListLine, CSVMapping.SokoZaikoCSV>(modeldatas, fileName);

            //バイトに変換しファイルをhttp出力
            byte[] fileBytes = System.IO.File.ReadAllBytes(filename);

            return File(fileBytes, "text/csv", fileName);
        }

    }
}

Convenience/Views/Zaiko/Index.cshtml
@using Convenience.Models.DataModels
@model Convenience.Models.ViewModels.Zaiko.ZaikoViewModel
@{
    ViewData["Title"] = "Soko";
}
<h2>倉庫在庫検索</h2>

<div class="container">
    <div class="form-group">
        <h3>キー入力部</h3>
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="d-md-flex justify-content-between">
                <div class="col-md-6 mb-3">
                    <div class="row">
                        <div class="col-2 text-center">
                            <p>ソート順位</p>
                        </div>
                        <div class="col-4">
                            <label asp-for="@Model.KeyEventList.FirstOrDefault()!.KeyEventData" class="control-label"></label>
                        </div>
                        <div class="col-2 text-center">
                        </div>
                    </div>
                    @for (int i = 0; i < @Model.KeyEventList.Length; i++) {
                        <div class="row mb-1">
                            <div class="col-2 text-center">
                                @(i + 1)
                            </div>
                            @{
                                var a = @Model.KeyEventList[i];
                            }
                            <div class="col-4">
                                <select asp-for="@Model.KeyEventList[i].KeyEventData" asp-items="@Model.KeyList" class="form-control">
                                    <option value="">-- 選択してください --</option>
                                </select>
                            </div>
                            @{
                                var b = @Model.KeyEventList[i];
                            }
                            <div class="col-2 form-check form-switch text-center">
                                <input asp-for="@Model.KeyEventList[i].Descending" type="checkbox" class="form-check-input" />
                                <label asp-for="@Model.KeyEventList[i].Descending"  class="form-check-label">降順</label>
                            </div>
                        </div>
                    }
                </div>
                <hr class="my-2 bg-primary">
                <div class="col-md-6 mb-3">
                    <div class="row">
                        <div class="col-2 text-center">
                            <p>検索キー</p>
                        </div>
                        <div class="col-4">
                            <label asp-for="@Model.SelecteWhereItemArray.FirstOrDefault()!.LeftSide" class="control-label"></label>
                        </div>
                        <div class="col-2 text-center">
                            <label asp-for="@Model.SelecteWhereItemArray.FirstOrDefault()!.ComparisonOperator" class="control-label"></label>
                        </div>
                        <div class="col-4">
                            <label asp-for="@Model.SelecteWhereItemArray.FirstOrDefault()!.RightSide" class="control-label"></label>
                        </div>
                    </div>
                    @for (int i = 0; i < Model.SelecteWhereItemArray.Count(); i++) {
                        <div class="row mb-1">
                            <div class="col-2 text-center">
                                @(i + 1)
                            </div>
                            <div class="col-4">
                                <select asp-for="@Model.SelecteWhereItemArray[i].LeftSide" asp-items="@Model.SelectWhereLeftSideList" class="form-control">
                                    <option value="">-- 選択してください --</option>
                                </select>
                            </div>
                            <div class="col-2 text-center">
                                <select asp-for="@Model.SelecteWhereItemArray[i].ComparisonOperator" asp-items="@Model.ComparisonOperatorList" class="form-control">
                                    <option value="==">=</option>
                                </select>
                            </div>
                            <div class="col-4">
                                <input asp-for="@Model.SelecteWhereItemArray[i].RightSide" class="form-control" />
                            </div>
                        </div>
                    }
                </div>
            </div>
            <input type="submit" value="検索" class="btn btn-primary" /></>
             @if (Model.ZaikoListLines != null && Model.ZaikoListLines.Count() > 0) {
                <!-- 「ダウンロード」ボタンのリンク -->
                <a href="@Url.Action("DownLoad", "Zaiko", new { index = 1 })" class="btn btn-primary">ダウンロード</a>
             }
        </form>
    </div>

    <hr class="my-2 bg-primary">

    @if (Model.ZaikoListLines != null && Model.ZaikoListLines.Count() > 0) {
        <div class="list-group">
            <table class="table table-striped table-bordered">
                <thead class="table-primary">
                    <tr>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.ShiireSakiId" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.ShiirePrdId" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.ShohinId" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.ShohinName" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.ChumonZan" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.SokoZaikoCaseSu" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.SokoZaikoSu" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.LastShiireDate" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.ZaikoListLines.FirstOrDefault()!.LastDeliveryDate" class="control-label"></label>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @for (var i = 0; i < Model.ZaikoListLines.Count; i++) {
                        <tr>
                            <td>
                                @Model.ZaikoListLines[i].ShiireSakiId
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].ShiirePrdId
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].ShohinId
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].ShohinName
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].ChumonZan
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].SokoZaikoCaseSu
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].SokoZaikoSu
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].LastShiireDate
                            </td>
                            <td>
                                @Model.ZaikoListLines[i].LastDeliveryDate
                            </td>
                        </tr>
                    }
                    <tr class="light-pink">
                        @{
                            var zk = Model.ZaikoLine;
                        }
                        <td>
                           合計
                        </td>
                        <td>
                            @zk.ShiirePrdId
                        </td>
                        <td>
                            @zk.ShohinId
                        </td>
                        <td class="text-end">
                            @zk.ShohinName
                            件
                        </td>
                        <td>
                            @zk.ChumonZan
                        </td>
                        <td>
                            @zk.SokoZaikoCaseSu
                        </td>
                        <td>
                            @zk.SokoZaikoSu
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}