Convenience/Models/DataModels/TentoZaiko.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#pragma warning disable CS8618

namespace Convenience.Models.DataModels {
    /// <summary>
    /// 店頭在庫
    /// </summary>
    /// <Remarks>
    /// 主キー：商品コード
    /// </Remarks>
    [Table("tento_zaiko")]
    [PrimaryKey(nameof(ShohinId))]
    public class TentoZaiko {

        [Column("shohin_code")]
        [DisplayName("商品コード")]
        [MaxLength(10)]
        [Required]
        [Key]
        public string ShohinId { get; set; }

        [Column("zaiko_su")]
        [DisplayName("店頭在庫数")]
        [Precision(7, 2)]
        public decimal ZaikoSu { get; set; }

        [Column("last_shiire_datetime")]
        [DisplayName("直近仕入日時")]
        [Required]
        [DataType(DataType.DateTime)]
        public DateOnly LastShireDateTime { get; set; }

        [Column("last_haraidashi_datetime")]
        [DisplayName("直近払出日時")]
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime? LastHaraidashiDate { get; set; }

        [Column("last_uriage_datetime")]
        [DisplayName("直近売上日時")]
        [DataType(DataType.DateTime)]
        public DateTime? LastUriageDatetime { get; set; }

        [ForeignKey(nameof(ShohinId))]
        public virtual ShohinMaster? ShohinMaster { get; set; }

        [Timestamp]
        public uint Version { get; set; }
    }
}

Convenience/Models/ViewModels/TentoZaiko/TentoZaIkoViewModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel.DataAreaClass;
using Newtonsoft.Json;
using Convenience.Models.Interfaces;
using static Convenience.Models.Interfaces.IRetrivalViewModel<Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel.DataAreaClass.TentoZaIkoLine>;
using static Convenience.Models.Interfaces.IRetrivalViewModel<Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel.DataAreaClass.TentoZaIkoLine>.IKeywordAreaClass;
using static Convenience.Models.Interfaces.IRetrivalViewModel<Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel.DataAreaClass.TentoZaIkoLine>.IKeywordAreaClass.ISortAreaClass;
using static Convenience.Models.Interfaces.IRetrivalViewModel<Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel.DataAreaClass.TentoZaIkoLine>.IKeywordAreaClass.IKeyAreaClass;
using static Convenience.Models.ViewModels.ChumonJisseki.ChumonJissekiViewModel.DataAreaClass;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Convenience.Models.ViewModels.TentoZaiko {

    /// <summary>
    /// 店頭在庫検索ビューモデル
    /// </summary>
    public class TentoZaikoViewModel : IRetrivalViewModel<TentoZaIkoLine> {

        /// <summary>
        /// ソートキー・検索キーエリア管理用
        /// </summary>
        public IKeywordAreaClass KeywordArea { get; set; }
        /// <summary>
        /// データ表示管理用
        /// </summary>
        public IDataAreaClass DataArea { get; set; }

        /// <summary>
        /// コンストラクタ
        /// ソート・検索キーエリア管理用オブジェクト初期化
        /// </summary>
        public TentoZaikoViewModel() {
            KeywordArea = new KeywordAreaClass();
            DataArea = new DataAreaClass();
        }

        /// <summary>
        /// ソートキー・検索キーエリア管理用クラス
        /// </summary>
        public class KeywordAreaClass : IKeywordAreaClass {
            /// <summary>
            /// ソートキーエリア管理用
            /// </summary>
            public ISortAreaClass SortArea { get; set; }
            /// <summary>
            /// 検索キーエリア管理用
            /// </summary>
            public IKeyAreaClass KeyArea { get; set; }
            
            /// <summary>
            /// コンストラクター
            /// ソートキーエリア・検索キーエリア管理用オブジェクト初期化
            /// </summary>
            public KeywordAreaClass() {
                this.SortArea = new SortAreaClass();
                this.KeyArea = new KeyAreaClass();
            }
            
            /// <summary>
            /// ソートエリア管理用クラス
            /// </summary>
            public class SortAreaClass : ISortAreaClass {
                /// <summary>
                /// ソートキー指示データ管理用
                /// </summary>
                public SortEventRec[] KeyEventList { get; set; }

                /// <summary>
                /// ソートキー一覧表示用
                /// </summary>
                [JsonIgnore]
                public SelectList KeyList { get; set; }

                /// <summary>
                /// ソートキー指示データ初期データセット
                /// </summary>
                public SortEventRec GetDefaltSortForSort(int index) {
                    return index switch {
                        0 => new SortEventRec(nameof(TentoZaIkoLine.ShohinId), false),
                        _ => new SortEventRec()
                    };
                }

                /// <summary>
                /// ソートキー入力最大行数
                /// </summary>
                public int LineCountForSelectorOfOrder { get; set; } = 6; //Order入力６行

                /// <summary>
                /// ソートキーエリア管理用クラス
                /// </summary>
                public SortAreaClass() {
                    /*
                     * 初期化
                     */
                    KeyEventList = new SortEventRec[LineCountForSelectorOfOrder];

                    KeyList = new SelectList(
                        new List<SelectListItem>
                        {
                            new() { Value = nameof(TentoZaIkoLine.ShohinId), Text = ISharedTools.GetDisplayName(typeof(TentoZaIkoLine), nameof(TentoZaIkoLine.ShohinId)) },
                            new() { Value = nameof(TentoZaIkoLine.ShohinName), Text = ISharedTools.GetDisplayName(typeof(TentoZaIkoLine), nameof(TentoZaIkoLine.ShohinName)) },
                            new() { Value = nameof(TentoZaIkoLine.ZaikoSu), Text = ISharedTools.GetDisplayName(typeof(TentoZaIkoLine), nameof(TentoZaIkoLine.ZaikoSu)) },
                            new() { Value = nameof(TentoZaIkoLine.LastShireDateTime), Text = ISharedTools.GetDisplayName(typeof(TentoZaIkoLine), nameof(TentoZaIkoLine.LastShireDateTime)) },
                            new() { Value = nameof(TentoZaIkoLine.LastHaraidashiDate), Text = ISharedTools.GetDisplayName(typeof(TentoZaIkoLine), nameof(TentoZaIkoLine.LastHaraidashiDate)) },
                            new() { Value = nameof(TentoZaIkoLine.LastUriageDatetime), Text = ISharedTools.GetDisplayName(typeof(TentoZaIkoLine), nameof(TentoZaIkoLine.LastUriageDatetime)) },
                        },
                        "Value",
                        "Text"
                    );

                    /*
                     * ソートキー指示データセット
                     */
                    ((ISortAreaClass)this).InitSortArea();
                }


            }

            /// <summary>
            /// 検索キー管理用クラス
            /// </summary>
            public class KeyAreaClass : IKeyAreaClass {

                /// <summary>
                /// Where入力リスト初期化
                /// </summary>
                public SelecteWhereItem[] SelecteWhereItemArray { get; set; }

                /// <summary>
                /// 検索キー入力最大行数
                /// </summary>
                public int LineCountForSelectorOfWhere { get; set; } = 6; //Where入力６行

                /// <summary>
                /// 比較演算子選択用
                /// </summary>
                /// 
                [JsonIgnore]
                public SelectList ComparisonOperatorList { get; set; }

                /// <summary>
                /// Where左辺用カラムセット用
                /// </summary>
                /// 
                [JsonIgnore]
                public SelectList SelectWhereLeftSideList { get; set; }

                /// <summary>
                /// 検索キー指示データ初期データセット
                /// </summary>
                public SelecteWhereItem GetDefaltSortForWhere(int index) {
                    return new SelecteWhereItem();
                }
                public KeyAreaClass() {
                    /*
                     * 初期化
                     */
                    SelecteWhereItemArray = new SelecteWhereItem[LineCountForSelectorOfWhere];
                    ComparisonOperatorList = new SelectList(new List<SelectListItem>());

                    /*
                     * 検索キー指示データ初期データセット
                     */

                    //処理なし

                    /*
                     *  検索キー一覧表示セット
                     */
                    SelectWhereLeftSideList = new SelectList(
                    new List<SelectListItem>{
                        new() { Value = nameof(TentoZaIkoLine.ShohinId), Text = "商品コード" },
                        new() { Value = nameof(TentoZaIkoLine.ShohinName), Text = "商品名" },
                        new() { Value = nameof(TentoZaIkoLine.ZaikoSu), Text = "店頭在庫数" },
                        new() { Value = nameof(TentoZaIkoLine.LastShireDateTime), Text = "直近仕入日時" },
                        new() { Value = nameof(TentoZaIkoLine.LastHaraidashiDate), Text = "直近払出日時" },
                        new() { Value = nameof(TentoZaIkoLine.LastUriageDatetime), Text = "直近売上日時" },
                    },
                    "Value",
                    "Text"
                );

                    /*
                     * 比較演算子一覧のセット
                     * 検索キーキー指示データセット
                    */
                    ((IKeyAreaClass)this).InitKeyArea();
                }
            }
        }

        /// <summary>
        /// データ表示管理用クラス
        /// </summary>
        public class DataAreaClass : IDataAreaClass {

            /// <summary>
            /// データ表示用リスト
            /// </summary>
            public IEnumerable<TentoZaIkoLine> Lines { get; set; }

            public TentoZaIkoLine SummaryLine { get; set; }

            /// <summary>
            /// コンストラクタ
            ///  データ表示用リストの初期化
            /// </summary>
            public DataAreaClass() {
                Lines = new List<TentoZaIkoLine>();
                SummaryLine = new TentoZaIkoLine();
            }

            /// <summary>
            /// データ表示用リストの１レコード定義
            /// </summary>
            public class TentoZaIkoLine {
                [DisplayName("商品コード")]
                [MaxLength(10)]
                [Required]
                public string? ShohinId { get; set; }

                [DisplayName("商品名称")]
                [MaxLength(10)]
                [Required]
                public string? ShohinName { get; set; }

                [Column("zaiko_su")]
                [DisplayName("店頭在庫数")]
                [Precision(7, 2)]
                public decimal ZaikoSu { get; set; }

                [Column("last_shiire_datetime")]
                [DisplayName("直近仕入日時")]
                [Required]
                [DataType(DataType.DateTime)]
                public DateOnly LastShireDateTime { get; set; }

                [Column("last_haraidashi_datetime")]
                [DisplayName("直近払出日時")]
                [Required]
                [DataType(DataType.DateTime)]
                public DateTime? LastHaraidashiDate { get; set; }

                [Column("last_uriage_datetime")]
                [DisplayName("直近売上日時")]
                [DataType(DataType.DateTime)]
                public DateTime? LastUriageDatetime { get; set; }

Convenience/Controllers/TentoZaikoController.cs
using Convenience.Data;
using Convenience.Models.Interfaces;
using Convenience.Models.Properties.Config;
using Convenience.Models.ViewModels.TentoZaiko;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel.DataAreaClass;

namespace Convenience.Controllers {
    /// <summary>
    /// 店頭在庫検索コントローラ
    /// </summary>
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class TentoZaikoController : Controller, ISharedTools {
        /// <summary>
        /// DBコンテキスト
        /// </summary>
        private readonly ConvenienceContext _context;

        /// <summary>
        /// サービスクラス引継ぎ用キーワード
        /// </summary>
        private static readonly string IndexName = "TentoZaikoViewModel";

        /// <summary>
        /// 店頭在庫検索サービスクラス（ＤＩ用）
        /// </summary>
        private readonly ITentoZaikoService tentoZaikoService;

        /// <summary>
        /// CSVファイル作成（ＤＩ用）
        /// </summary>
        private readonly IConvertObjectToCsv _convertObjectToCsv;

        /// <summary>
        /// ビュー・モデル
        /// </summary>
        private readonly TentoZaikoViewModel tentoZaikoViewModel;
        /// <summary>
        /// １ページの行数
        /// </summary>
        private const int PageSize = 100;

        /// <summary>
        /// コンストラクター
        /// </summary>
        /// <param name="context">DBコンテキスト</param>
        /// <param name="tentoZaikoService">店頭在庫検索サービスクラスＤＩ注入用</param>
        public TentoZaikoController(ConvenienceContext context, ITentoZaikoService tentoZaikoService, IConvertObjectToCsv convertObjectToCsv) {
            this._context = context;
            this.tentoZaikoService = tentoZaikoService;
            this._convertObjectToCsv = convertObjectToCsv;
            this.tentoZaikoViewModel = new TentoZaikoViewModel();
        }

        /// <summary>
        /// 店頭在庫検索１枚目の初期表示処理
        /// </summary>
        /// <returns>店頭在庫ビューモデル（初期表示）</returns>
        [HttpGet]
        [Authorize]
        public Task<IActionResult> Index() {
            ViewBag.HandlingFlg = "FirstDisplay";
            //最初のカーソル位置
            ViewBag.FocusPosition = "#KeywordArea_KeyArea_SelecteWhereItemArray_0__LeftSide";

            //最初のカーソル位置
            return Task.FromResult<IActionResult>(View("Index", tentoZaikoViewModel));
        }

        /// <summary>
        /// 店頭在庫検索キー入力後
        /// </summary>
        /// <param name="postedTentoZaikoViewModel">店頭在庫ビューモデル(post)</param>
        /// <returns>店頭在庫ビューモデル</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Result(TentoZaikoViewModel postedTentoZaikoViewModel, int page = 1
            ) {
            return await ProcessResult(postedTentoZaikoViewModel, page, PageSize);
        }

        /// <summary>
        /// 検索結果
        /// </summary>
        /// <param name="page">ページ番号</param>
        /// <returns>店頭在庫検索ビュー</returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Result(int page) {
            if (TempData.Peek(IndexName) is string tempDataStr) {
                TentoZaikoViewModel.KeywordAreaClass keyArea = ISharedTools.ConvertFromSerial<TentoZaikoViewModel.KeywordAreaClass>(tempDataStr);
                tentoZaikoViewModel.KeywordArea = keyArea;

                return await ProcessResult(tentoZaikoViewModel, page, PageSize);
            }
            else {
                // TempDataがない場合、初期ページにリダイレクト
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Download
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Downloadファイル</returns>
        /// <exception cref="Exception"></exception>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DownLoad() {
            TentoZaikoViewModel.KeywordAreaClass keywordArea
                = ISharedTools.ConvertFromSerial<TentoZaikoViewModel.KeywordAreaClass>(TempData.Peek(IndexName)?.ToString() ?? throw new Exception("tempdataなし"));
            tentoZaikoViewModel.KeywordArea = keywordArea;

            // 店頭在庫検索
            TentoZaikoViewModel createdTentoZaikoViewModel = await tentoZaikoService.TentoZaikoRetrival(tentoZaikoViewModel);

            //このコントローラの名前を認識
            string fileName = _convertObjectToCsv.GetFileName(this.GetType().Name);

            //モデルデータを取り出すし、ＣＳＶに変換
            IEnumerable<TentoZaIkoLine> modeldatas = createdTentoZaikoViewModel.DataArea.Lines;
            string filename = _convertObjectToCsv.ConvertToCSV<TentoZaIkoLine, CSVMapping.TentoZaIkoCSV>(modeldatas, fileName);

            //バイトに変換しファイルをhttp出力
            byte[] fileBytes = System.IO.File.ReadAllBytes(filename);

            return File(fileBytes, "text/csv", fileName);
        }
        /// <summary>
        ///  検索データ作成
        /// </summary>
        /// <param name="tentoZaikoViewModel">店頭在庫ビューモデル</param>
        /// <param name="page">ページ番号</param>
        /// <param name="pageSize">行数/ページ</param>
        /// <returns></returns>
        private async Task<IActionResult> ProcessResult(TentoZaikoViewModel tentoZaikoViewModel, int page, int pageSize) {
            // 店頭在庫検索
            TentoZaikoViewModel createdTentoZaikoViewModel = await tentoZaikoService.TentoZaikoRetrival(tentoZaikoViewModel);

            // ページング処理
            int totalLines = createdTentoZaikoViewModel.DataArea.Lines.Count();
            ViewBag.TotalPages = Math.Ceiling((double)totalLines / pageSize);
            ViewBag.CurrentPage = page;

            createdTentoZaikoViewModel.DataArea.Lines =
                createdTentoZaikoViewModel.DataArea.Lines.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // キーワードエリアの保存
            TempData[IndexName] = ISharedTools.ConvertToSerial(createdTentoZaikoViewModel.KeywordArea);

            //最初のカーソル位置
            ViewBag.FocusPosition = "#KeywordArea_KeyArea_SelecteWhereItemArray_0__LeftSide";
            // 結果をビューに返す
            ViewBag.HandlingFlg = "SecondDisplay";
            return View("Index", createdTentoZaikoViewModel);
        }

    }
}

Convenience/Views/TentoZaiko/Index.cshtml
@model Convenience.Models.ViewModels.TentoZaiko.TentoZaikoViewModel
@{
    ViewData["Title"] = "店頭在庫";
}

<h2>@ViewData["Title"]</h2>

<div class="container">
    <div class="form-group">
        <form asp-action="Result" id="need-collapse-at-retrival">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="accordion">
                <div class="accordion-item">
                    <h5 class="accordion-header" id="headingOne">
                        <button class="accordion-button bg-light text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <h3>キー入力</h3>
                        </button>
                    </h5>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordion">
                        <div class="accordion-body">
                            <div class="d-md-flex justify-content-between">
                                <div class="col-md-6 mb-3">
                                    <div class="row">
                                        <div class="col-2 text-center">
                                            <p>ソート順位</p>
                                        </div>
                                        <div class="col-4">
                                            <label asp-for="@Model.KeywordArea.SortArea.KeyEventList.FirstOrDefault()!.KeyEventData" class="control-label"></label>
                                        </div>
                                        <div class="col-2">
                                            <label asp-for="@Model.KeywordArea.SortArea.KeyEventList.FirstOrDefault()!.Descending" class="control-label"></label>
                                        </div>
                                        <div class="col-2">
                                        </div>
                                    </div>
                                    @for (int i = 0; i < @Model.KeywordArea.SortArea.KeyEventList.Length; i++) {
                                        <div class="row mb-1">
                                            <div class="col-2 d-flex justify-content-center align-items-center">
                                                @(i + 1)
                                            </div>
                                            <div class="col-4">
                                                <select asp-for="@Model.KeywordArea.SortArea.KeyEventList[i].KeyEventData" asp-items="@Model.KeywordArea.SortArea.KeyList" class="form-control">
                                                    <option value="">-- 選択してください --</option>
                                                </select>
                                            </div>
                                            <div class="col-2 d-flex justify-content-center align-items-center form-check form-switch">
                                                <input asp-for="@Model.KeywordArea.SortArea.KeyEventList[i].Descending" type="checkbox" class="form-check-input" />
                                            </div>
                                            <div class="col-2">
                                            </div>
                                        </div>
                                    }
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="row">
                                        <div class="col-2 text-center">
                                            <p>検索キー</p>
                                        </div>
                                        <div class="col-4">
                                            <label asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray.FirstOrDefault()!.LeftSide" class="control-label"></label>
                                        </div>
                                        <div class="col-2 text-center">
                                            <label asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray.FirstOrDefault()!.ComparisonOperator" class="control-label"></label>
                                        </div>
                                        <div class="col-4">
                                            <label asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray.FirstOrDefault()!.RightSide" class="control-label"></label>
                                        </div>
                                    </div>
                                    @for (int i = 0; i < @Model.KeywordArea.KeyArea.SelecteWhereItemArray.Length; i++) {
                                        <div class="row mb-1">
                                            <div class="col-2 d-flex justify-content-center align-items-center">
                                                @(i + 1)
                                            </div>
                                            <div class="col-4">
                                                <select asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray[i].LeftSide" asp-items="@Model.KeywordArea.KeyArea.SelectWhereLeftSideList" class="form-control">
                                                    <option value="">-- 選択してください --</option>
                                                </select>
                                            </div>
                                            <div class="col-2">
                                                <select asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray[i].ComparisonOperator" asp-items="@Model.KeywordArea.KeyArea.ComparisonOperatorList" class="form-control text-center">
                                                </select>
                                            </div>
                                            <div class="col-4">
                                                    <input asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray[i].RightSide" class="form-control">
                                                </input>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                            <input id="submit_btn_for_retrival" type="submit" value="検索" class="btn btn-primary" /></input>
                            @if ((Model.DataArea.Lines?.Count() ?? 0) > 0) {
                                <a href="@Url.Action("DownLoad", "TentoZaiko", new { index = 1 })" class="btn btn-primary">ダウンロード</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    @if ((Model.DataArea.Lines?.Count() ?? 0) > 0) {
        <div class="list-group mt-1">
            <table class="table table-striped table-bordered">
                <thead class="table-primary">
                    <tr>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ShohinId" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ShohinName" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ZaikoSu" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.LastShireDateTime" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.LastHaraidashiDate" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.LastUriageDatetime" class="control-label"></label>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.DataArea.Lines!) {
                        <tr>
                            <td>
                                @item.ShohinId
                            </td>
                            <td>
                                @item.ShohinName
                            </td>
                            <td>
                                @item.ZaikoSu
                            </td>
                            <td>
                                @item.LastShireDateTime
                            </td>
                            <td>
                                @item.LastHaraidashiDate
                            </td>
                            <td>
                                @item.LastUriageDatetime
                            </td>

                        </tr>
                    }
                    @{
                        var tz = Model.DataArea.SummaryLine;
                    }
                    <tr class="light-pink">
                        <td>
                            合計
                        </td>
                        <td>
                            @tz.ShohinName
                            件
                        </td>
                        <td>
                            @tz.ZaikoSu
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>

                    </tr>
            </tbody>
        </table>
    </div>
    <div class="pagination justify-content-center">
        @if (ViewBag.CurrentPage > 1) {
        <a href="@Url.Action("Result", "TentoZaiko", new { page = ViewBag.CurrentPage - 1 })" class="page-link">前へ</a>
        }

        <ul class="pagination">
            @for (int i = 1; i <= ViewBag.TotalPages; i++) {
            <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                <a href="@Url.Action("Result", "TentoZaiko", new { page = i })" class="page-link">
                    @i
                </a>
            </li>
}
        </ul>

        @if (ViewBag.CurrentPage < ViewBag.TotalPages) {
        <a href="@Url.Action("Result", "TentoZaiko", new { page = ViewBag.CurrentPage + 1 })" class="page-link">次へ</a>
}
    </div>
    }
</div>
<!-- 初期表示か・更新後の再表示か-->
<div id="handlingFlg" data-message="@ViewBag.HandlingFlg"></div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/sites.js"></script>
    <script>
        $(document).ready(function () {
            AccordionHandller();
            RendaSolution();
            GetShohinName();
            FirstFocus('@ViewBag.FocusPosition');
            //ResetForm("need-collapse-at-retrival");
            //PreventModoru();
        });
    </script>
}