Convenience/Models/DataModels/KaikeiJisseki.cs
using Convenience.Models.Interfaces;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#pragma warning disable CS8618

namespace Convenience.Models.DataModels {

    /// <summary>
    /// 会計実績DTO
    /// </summary>
    /// <Remarks>
    /// 主キー：商品コード、売上日時
    /// </Remarks>
    [Table("kaikei_jisseki")]
    [PrimaryKey(nameof(UriageDatetimeId),nameof(ShohinId))]
    public class KaikeiJisseki : IKaikeiJissekiForAdd {

        [Column("uriage_datetimeid")]
        [DisplayName("売上日時コード")]
        [MaxLength(20)]
        [Required]
        public string UriageDatetimeId { get; set; }

        [Column("shohin_code")]
        [DisplayName("商品コード")]
        [MaxLength(10)]
        [Required]
        public string? ShohinId { get; set; }

        [Column("uriage_datetime")]
        [DisplayName("売上日時")]
        [DataType(DataType.DateTime)]
        [Required]
        public DateTime UriageDatetime { get; set; }

        [Column("uriage_su")]
        [DisplayName("売上数量")]
        [Required]
        [Precision(10, 2)]
        public decimal UriageSu { get; set; }

        [Column("uriage_kingaku")]
        [DisplayName("売上金額")]
        [Required]
        [Precision(15, 2)]
        public decimal UriageKingaku { get; set; }

        [Column("zeikomi_kingaku")]
        [DisplayName("税込金額")]
        [Required]
        [Precision(15, 2)]
        public decimal ZeikomiKingaku { get; set; }

        [Column("shohin_tanka")]
        [DisplayName("商品単価")]
        [Required]
        [Precision(15, 2)]
        public decimal ShohinTanka { get; set; }

        [Column("shohi_zeiritsu")]
        [DisplayName("消費税率")]
        [Required]
        [Precision(15, 2)]
        public decimal ShohiZeiritsu { get; set; }

        [Column("naigai_class")]
        [DisplayName("内外区分")]
        [Required]
        [MaxLength(1)]
        public string NaigaiClass { get; set; } = "0";

        [Column("kaikei_seq")]
        [DisplayName("会計順位")]
        [Required]
        public int KaikeiSeq { get; set; }

        [ForeignKey(nameof(UriageDatetimeId))]
        public  KaikeiHeader KaikeiHeader { get; set; }

        [ForeignKey(nameof(ShohinId))]
        public ShohinMaster? ShohinMaster { get; set; }

        [ForeignKey(nameof(NaigaiClass))]
        public NaigaiClassMaster? NaigaiClassMaster { get; set; }

        public TentoZaiko? TentoZaiko { get; set; }
    }
}

Convenience/Controllers/KaikeiJissekiController.cs
using Convenience.Data;
using Convenience.Models.Interfaces;
using Convenience.Models.Properties.Config;
using Convenience.Models.ViewModels.KaikeiJisseki;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Convenience.Models.ViewModels.KaikeiJisseki.KaikeiJissekiViewModel.DataAreaClass;

namespace Convenience.Controllers {
    /// <summary>
    /// 会計実績検索コントローラ
    /// </summary>
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public class KaikeiJissekiController : Controller, ISharedTools {
        /// <summary>
        /// DBコンテキスト
        /// </summary>
        private readonly ConvenienceContext _context;

        /// <summary>
        /// サービスクラス引継ぎ用キーワード
        /// </summary>
        private static readonly string IndexName = "KaikeiJissekiViewModel";

        /// <summary>
        /// 会計実績検索サービスクラス（ＤＩ用）
        /// </summary>
        private readonly IKaikeiJissekiService kaikeiJissekiService;

        /// <summary>
        /// CSVファイル作成（ＤＩ用）
        /// </summary>
        private readonly IConvertObjectToCsv _convertObjectToCsv;

        /// <summary>
        /// ビュー・モデル
        /// </summary>
        private readonly KaikeiJissekiViewModel kaikeiJissekiViewModel;
        /// <summary>
        /// １ページの行数
        /// </summary>
        private const int PageSize = 100;

        /// <summary>
        /// コンストラクター
        /// </summary>
        /// <param name="context">DBコンテキスト</param>
        /// <param name="kaikeiJissekiService">会計実績検索サービスクラスＤＩ注入用</param>
        public KaikeiJissekiController(ConvenienceContext context, IKaikeiJissekiService kaikeiJissekiService, IConvertObjectToCsv convertObjectToCsv) {
            this._context = context;
            this.kaikeiJissekiService = kaikeiJissekiService;
            this.kaikeiJissekiViewModel = new KaikeiJissekiViewModel();
            this._convertObjectToCsv = convertObjectToCsv;
        }

        /// <summary>
        /// 会計実績検索１枚目の初期表示処理
        /// </summary>
        /// <returns>会計実績ビューモデル（初期表示）</returns>
        /// 
        [HttpGet]
        [Authorize]
        public Task<IActionResult> Index() {
            ViewBag.HandlingFlg = "FirstDisplay";
            //最初のカーソル位置
            ViewBag.FocusPosition = "#KeywordArea_KeyArea_SelecteWhereItemArray_0__LeftSide";

            //最初のカーソル位置
            return Task.FromResult<IActionResult>(View("Index", kaikeiJissekiViewModel));
        }

        /// <summary>
        /// 会計実績検索キー入力後
        /// </summary>
        /// <param name="postedTentoZaikoViewModel"></param>
        /// <returns>会計実績ビューモデル</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Result(KaikeiJissekiViewModel postedKaikeiJissekiViewModel, int page = 1
            ) {
            return await ProcessResult(postedKaikeiJissekiViewModel, page, PageSize);
        }

        /// <summary>
        /// 検索結果
        /// </summary>
        /// <param name="page"></param>
        /// <returns>会計実績検索ビュー</returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Result(int page) {
            if (TempData.Peek(IndexName) is string tempDataStr) {
                KaikeiJissekiViewModel.KeywordAreaClass keyArea = ISharedTools.ConvertFromSerial<KaikeiJissekiViewModel.KeywordAreaClass>(tempDataStr);
                kaikeiJissekiViewModel.KeywordArea = keyArea;

                return await ProcessResult(kaikeiJissekiViewModel, page, PageSize);
            }
            else {
                // TempDataがない場合、初期ページにリダイレクト
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Download
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Downloadファイル</returns>
        /// <exception cref="Exception"></exception>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DownLoad() {
            KaikeiJissekiViewModel.KeywordAreaClass keywordArea
                = ISharedTools.ConvertFromSerial<KaikeiJissekiViewModel.KeywordAreaClass>(TempData.Peek(IndexName)?.ToString() ?? throw new Exception("tempdataなし"));
            kaikeiJissekiViewModel.KeywordArea = keywordArea;

            // 会計実績検索
            KaikeiJissekiViewModel createdKaikeiJissekiViewModel = await kaikeiJissekiService.KaikeiJissekiRetrival(kaikeiJissekiViewModel);

            //このコントローラの名前を認識
            string fileName = _convertObjectToCsv.GetFileName(this.GetType().Name);

            //モデルデータを取り出すし、ＣＳＶに変換
            IEnumerable<KaikeiJissekiLineClass> modeldatas = createdKaikeiJissekiViewModel.DataArea.Lines;
            string filename = _convertObjectToCsv.ConvertToCSV<KaikeiJissekiLineClass, CSVMapping.KaikeiJissekiCSV>(modeldatas, fileName);

            //バイトに変換しファイルをhttp出力
            byte[] fileBytes = System.IO.File.ReadAllBytes(filename);

            return File(fileBytes, "text/csv", fileName);
        }

        /// <summary>
        /// 検索データ作成
        /// </summary>
        /// <param name="kaikeiJissekiViewModel">会計実績検索ビューモデル</param>
        /// <param name="page">ページ番号</param>
        /// <param name="pageSize">行数／ページ</param>
        /// <returns>会計実績検索ビュー</returns>
        private async Task<IActionResult> ProcessResult(KaikeiJissekiViewModel kaikeiJissekiViewModel, int page, int pageSize) {
            // 会計実績検索
            KaikeiJissekiViewModel createdKaikeiJissekiViewModel = await kaikeiJissekiService.KaikeiJissekiRetrival(kaikeiJissekiViewModel);

            // ページング処理
            int totalLines = createdKaikeiJissekiViewModel.DataArea.Lines.Count();
            ViewBag.TotalPages = Math.Ceiling((double)totalLines / pageSize);
            ViewBag.CurrentPage = page;

            createdKaikeiJissekiViewModel.DataArea.Lines =
                createdKaikeiJissekiViewModel.DataArea.Lines.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // キーワードエリアの保存
            TempData[IndexName] = ISharedTools.ConvertToSerial(createdKaikeiJissekiViewModel.KeywordArea);

            //最初のカーソル位置
            ViewBag.FocusPosition = "#KeywordArea_KeyArea_SelecteWhereItemArray_0__LeftSide";
            // 結果をビューに返す
            ViewBag.HandlingFlg = "SecondDisplay";
            return View("Index", createdKaikeiJissekiViewModel);
        }

    }
}

Convenience/Views/KaikeiJisseki/Index.cshtml
@model Convenience.Models.ViewModels.KaikeiJisseki.KaikeiJissekiViewModel
@{
    ViewData["Title"] = "会計実績";
}

<h2>@ViewData["Title"]</h2>

<div class="container">
    <div class="form-group">
        <form asp-action="Result" id="need-collapse-at-retrival">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div id="accordion">
                <div class="accordion-item">
                    <h5 class="accordion-header" id="headingOne">
                        <button class="accordion-button bg-light text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <h3>キー入力</h3>
                        </button>
                    </h5>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordion">
                        <div class="accordion-body">
                            <div class="d-md-flex justify-content-between">
                                <div class="col-md-6 mb-3">
                                    <div class="row">
                                        <div class="col-2 text-center">
                                            <p>ソート順位</p>
                                        </div>
                                        <div class="col-4">
                                            <label asp-for="@Model.KeywordArea.SortArea.KeyEventList.FirstOrDefault()!.KeyEventData" class="control-label"></label>
                                        </div>
                                        <div class="col-2">
                                            <label asp-for="@Model.KeywordArea.SortArea.KeyEventList.FirstOrDefault()!.Descending" class="control-label"></label>
                                        </div>
                                        <div class="col-2">
                                        </div>
                                    </div>
                                    @for (int i = 0; i < @Model.KeywordArea.SortArea.KeyEventList.Length; i++) {
                                        <div class="row mb-1">
                                            <div class="col-2 d-flex justify-content-center align-items-center">
                                                @(i + 1)
                                            </div>
                                            <div class="col-4">
                                                <select asp-for="@Model.KeywordArea.SortArea.KeyEventList[i].KeyEventData" asp-items="@Model.KeywordArea.SortArea.KeyList" class="form-control">
                                                    <option value="">-- 選択してください --</option>
                                                </select>
                                            </div>
                                            <div class="col-2 d-flex justify-content-center align-items-center form-check form-switch">
                                                <input asp-for="@Model.KeywordArea.SortArea.KeyEventList[i].Descending" type="checkbox" class="form-check-input" />
                                            </div>
                                            <div class="col-2">
                                            </div>
                                        </div>
                                    }
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="row">
                                        <div class="col-2 text-center">
                                            <p>検索キー</p>
                                        </div>
                                        <div class="col-4">
                                            <label asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray.FirstOrDefault()!.LeftSide" class="control-label"></label>
                                        </div>
                                        <div class="col-2 text-center">
                                            <label asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray.FirstOrDefault()!.ComparisonOperator" class="control-label"></label>
                                        </div>
                                        <div class="col-4">
                                            <label asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray.FirstOrDefault()!.RightSide" class="control-label"></label>
                                        </div>
                                    </div>
                                    @for (int i = 0; i < @Model.KeywordArea.KeyArea.SelecteWhereItemArray.Length; i++) {
                                        <div class="row mb-1">
                                            <div class="col-2 d-flex justify-content-center align-items-center">
                                                @(i + 1)
                                            </div>
                                            <div class="col-4">
                                                <select asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray[i].LeftSide" asp-items="@Model.KeywordArea.KeyArea.SelectWhereLeftSideList" class="form-control">
                                                    <option value="">-- 選択してください --</option>
                                                </select>
                                            </div>
                                            <div class="col-2">
                                                <select asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray[i].ComparisonOperator" asp-items="@Model.KeywordArea.KeyArea.ComparisonOperatorList" class="form-control text-center">
                                                </select>
                                            </div>
                                            <div class="col-4">
                                                <input asp-for="@Model.KeywordArea.KeyArea.SelecteWhereItemArray[i].RightSide" class="form-control">
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                            <input id="submit_btn_for_retrival" type="submit" value="検索" class="btn btn-primary" />
                             @if ((Model.DataArea.Lines?.Count() ?? 0) > 0) {
                                <a href="@Url.Action("DownLoad", "KaikeiJisseki", new { index = 1 })" class="btn btn-primary">ダウンロード</a>
                             }
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    @if ((Model.DataArea.Lines?.Count() ?? 0) > 0) {
        <div class="list-group mt-1">
            <table class="table table-striped table-bordered">
                <thead class="table-primary">
                    <tr>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.UriageDatetime" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ShohinId" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ShohinName" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.UriageSu" class="control-label text-end"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.UriageKingaku" class="control-label text-end"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ZeikomiKingaku" class="control-label text-end"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ShohinTanka" class="control-label text-end"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.ShohiZeiritsu" class="control-label text-end"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.NaigaiClass" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.DataArea.Lines!.FirstOrDefault()!.NaigaiClassName" class="control-label"></label>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.DataArea.Lines!) {
                        <tr>
                            <td>
                                @item.UriageDatetime
                            </td>
                            <td>
                                @item.ShohinId
                            </td>
                            <td>
                                @item.ShohinName
                            </td>
                            <td class="text-end">
                                @item.UriageSu
                            </td>
                            <td class="text-end">
                                @item.UriageKingaku
                            </td>
                            <td class="text-end">
                                @item.ZeikomiKingaku
                            </td>
                            <td class="text-end">
                                @item.ShohinTanka
                            </td>
                            <td class="text-end">
                                @item.ShohiZeiritsu
                            </td>
                            <td>
                                @item.NaigaiClass
                            </td>
                            <td>
                                @item.NaigaiClassName
                            </td>
                        </tr>
                    }
                </tbody>
                @{
                    var kj = Model.DataArea.SummaryLine;
                }
                <tr class="light-pink">
                    <td>
                      合計
                    </td>
                    <td>
                        @kj.ShohinId
                    </td>
                    <td class="text-end">
                        @kj.ShohinName
                        件
                    </td>
                    <td class="text-end">
                        @kj.UriageSu
                    </td>
                    <td class="text-end">
                        @kj.UriageKingaku
                    </td>
                    <td class="text-end">
                        @kj.ZeikomiKingaku
                    </td>
                    <td class="text-end">
                        @kj.ShohinTanka
                    </td>
                    <td class="text-end">
                        @kj.ShohiZeiritsu
                    </td>
                    <td>
                        
                    </td>
                    <td>
                        @kj.NaigaiClassName
                    </td>
                </tr>
            </table>
        </div>
        <div class="pagination justify-content-center">
            @if (ViewBag.CurrentPage > 1) {
                <a href="@Url.Action("Result", "KaikeiJisseki", new { page = ViewBag.CurrentPage - 1 })" class="page-link">前へ</a>
            }

            <ul class="pagination">
                @for (int i = 1; i <= ViewBag.TotalPages; i++) {
                    <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                        <a href="@Url.Action("Result", "KaikeiJisseki", new { page = i })" class="page-link">
                            @i
                        </a>
                    </li>
                }
            </ul>

            @if (ViewBag.CurrentPage < ViewBag.TotalPages) {
                <a href="@Url.Action("Result", "KaikeiJisseki", new { page = ViewBag.CurrentPage + 1 })" class="page-link">次へ</a>
            }
        </div>
    }
</div>
<!-- 初期表示か・更新後の再表示か-->
<div id="handlingFlg" data-message="@ViewBag.HandlingFlg"></div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/sites.js"></script>
    <script>
        $(document).ready(function () {
            AccordionHandller();
            RendaSolution();
            GetShohinName();
            FirstFocus('@ViewBag.FocusPosition');
            //ResetForm("need-collapse-at-retrival");
            //PreventModoru();
        });
    </script>
}